pub mod bitflip;
pub mod chalk_med;
pub mod extra_candies;
pub mod flowered_plant;
pub mod gcd_string;
pub mod linked_list_binary;
pub mod linked_list_insert_gcd;
pub mod linked_list_remove_nums;
pub mod merge_alt;
pub mod missing_obs;
pub mod spiral_linkedlist;
pub mod split_linkedlist;
pub mod sum_of_digit_string;
pub mod twosum;
pub mod vowel_replace;
pub mod walking_robot;

pub mod consistent_string_easy;
pub mod different_ways_to_add_parentheses_med;
pub mod kmp_longest_suffx_also_prefix_hard;
pub mod largest_number_string_med;
pub mod longest_subarray_with_max_bitwise_and_med;
pub mod longest_substring_containing_vowels_even_med;
pub mod minimum_time_diff_med;
pub mod uncommon_words_easy;
pub mod xor_subarray_medium;

pub mod lexicographic_numbers_medium;
pub mod lexicographic_hard;
